CREATE TABLE USERS(ID INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRES,A_PATERNO,A_MATERNO,DOMICILIO,CORREO,CONTRASENA);
INSERT INTO USERS (NOMBRES,A_PATERNO,A_MATERNO,DOMICILIO,CORREO,CONTRASENA)
VALUES ("edgar humberto","perez","martinez","loma bonita","devil97humper@gmail.com","123456");

SELECT * FROM USERS;
SELECT * FROM Users WHERE CORREO = 'juan@gmail.com'

DELETE  FROM USERS WHERE ID = 2

DROP TABLE USERS;